version: 2.1 
jobs:
  build-and-test:
    docker:
      - image: cimg/base:2022.09
    steps:
      - checkout
      - run: make deps
      - run: make lint
      - run: make test
      - run: make docker_build
workflows:
  basic:
    jobs:
      - build-and-test